### ISSUE TITLE
CLI Play command validation

### ISSUE THREAD

**Issue by lacf95** [cesarpmaster/music_player_py#3]
#### Description
As user I would like to be prompted by a message saying that I need to send at least one `file_path`
The application should raise an error saying:
```
Play command requires at least one argument
```

#### Notes
Expected input:
```
./music-player play
```

Expected output:
```
Play command requires at least one argument
```

Expected input:
```
./music-player play music_file.mp3
```

Expected output:
```
Playing music-file.mp3
```

**Comment by cesarpmaster** [comment]
Hello Adrian,

We updated the code to raise the value exceptions wanted  for this request

Regards,
